// The checksum "Flags" field is used to convey service options or extension negotiation information
// The following context establishment flags are defined in [RFC2744]
// Flag Name              Value
// ---------------------------------
GSS_C_DELEG_FLAG           1
GSS_C_MUTUAL_FLAG          2
GSS_C_REPLAY_FLAG          4
GSS_C_SEQUENCE_FLAG        8
GSS_C_CONF_FLAG           16
GSS_C_INTEG_FLAG          32
