scgi_local = /users/bozo_deluxe/rtorrent/rpc.socket
server.modules += ( "mod_scgi" )
scgi.server = (
                "/RPC2" =>
                  ( "127.0.0.1" =>
                    (
                      "socket" => "~/rtorrent/rpc.socket",
                      "check-local" => "disable",
                      "disable-time" => 0, 
                    )
                  )
              )
